### ISSUE TITLE
Please provide more tutorial

### ISSUE THREAD

**Issue by CanCanZeng** [ShuweiShao/NDDepth#1]
Hi, thank you for openning this project.
I test this algorithm on ubuntu20.04, and successfully installed the environment after fixing lots of dependency error. But I still cannot run demo.py, there will an error when running from video
`TypeError: forward() missing 2 required positional arguments: 'inv_K' and 'epoch'`
after changing this line https://github.com/ShuweiShao/NDDepth/blob/8c47ce9632fcc0a08e52529c1cf33cd449ebb18b/Estimation/nddepth/demo.py#L283 to `depth_est = self.model(image, new_camera_matrix, 5)`, there will be another error says 
```
    normalized_points = torch.matmul(inv_K[:, :3, :3], self.pix_coords)
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
```
I did not debug further.

Can you please provide more tutorial on this algorithm? Especially for depth completion, thanks in advance!

**Comment by ShuweiShao** [comment]
Sorry for the error! The demo.py is directly copied from NeWCRFs and not changed to our form. You can try the eval.py to reproduce the quantitative results. The code of depth completion will be released in the future.

**Comment by CanCanZeng** [comment]
Thank you for your quick reply, I will try eval.py later. And when will you give an example for depth completion?

**Comment by CanCanZeng** [comment]
Hi, I'd like to test this algorithm on my own data, so I revised the eval.py file to test on a single image. But the result is rather poor, I do not know where I made a mistake, can you help me?
The rgb and predicted depth and normal map as follows:
![rgb](https://github.com/ShuweiShao/NDDepth/assets/26817559/93297126-500a-4502-a7cd-6bb1c005bab1)
![depth](https://github.com/ShuweiShao/NDDepth/assets/26817559/a4c5f9f7-5457-4de2-ac6c-23617fc1b00c)
![normals](https://github.com/ShuweiShao/NDDepth/assets/26817559/81f7fe22-3617-4141-9836-10d2dad59f20)


and my test.py file as follows:
```
import torch
import torch.backends.cudnn as cudnn

import os, sys
import argparse
import numpy as np
from tqdm import tqdm

from utils import post_process_depth, flip_lr, compute_errors
from networks.NewCRFDepth import NewCRFDepth

from PIL import Image
from torchvision import transforms
import cv2

def convert_arg_line_to_args(arg_line):
    for arg in arg_line.split():
        if not arg.strip():
            continue
        yield arg


parser = argparse.ArgumentParser(description='NDDepth PyTorch implementation.', fromfile_prefix_chars='@')
parser.convert_arg_line_to_args = convert_arg_line_to_args

parser.add_argument('--model_name',                type=str,   help='model name', default='nddepth')
parser.add_argument('--encoder',                   type=str,   help='type of encoder, base07, large07, tiny07', default='large07')
parser.add_argument('--checkpoint_path',           type=str,   help='path to a checkpoint to load', default='')

# Dataset
parser.add_argument('--dataset',                   type=str,   help='dataset to train on, kitti or nyu', default='nyu')
parser.add_argument('--max_depth',                 type=float, help='maximum depth in estimation', default=10)

# Preprocessing
parser.add_argument('--do_random_rotate',                      help='if set, will perform random rotation for augmentation', action='store_true')
parser.add_argument('--degree',                    type=float, help='random rotation maximum degree', default=2.5)
parser.add_argument('--do_kb_crop',                            help='if set, crop input images as kitti benchmark images', action='store_true')
parser.add_argument('--use_right',                             help='if set, will randomly use right images when train on KITTI', action='store_true')

# Eval
parser.add_argument('--min_depth_eval',            type=float, help='minimum depth for evaluation', default=1e-3)
parser.add_argument('--max_depth_eval',            type=float, help='maximum depth for evaluation', default=80)
parser.add_argument('--eigen_crop',                            help='if set, crops according to Eigen NIPS14', action='store_true')
parser.add_argument('--garg_crop',                             help='if set, crops according to Garg  ECCV16', action='store_true')

# Test
parser.add_argument('--test_image_path',            type=str, help='test image path', default="")


if sys.argv.__len__() == 2:
    arg_filename_with_prefix = '@' + sys.argv[1]
    args = parser.parse_args([arg_filename_with_prefix])
else:
    args = parser.parse_args()

if args.dataset == 'kitti' or args.dataset == 'nyu':
    from dataloaders.dataloader import NewDataLoader


def test(model, image_path, epoch=5, post_process=False):
    image = np.asarray(Image.open(image_path), dtype=np.float32) / 255.0
    image = torch.from_numpy(image.transpose((2, 0, 1)))
    image = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])(image)
    image = image.unsqueeze(0)
    
    b, c, h, w =  image.shape 
    
    K = np.array([[500, 0, w / 2.0, 0],
                    [0, 500, h / 2.0, 0],
                    [0, 0, 1, 0],
                    [0, 0, 0, 1]], dtype=np.float32)
    inv_K = np.linalg.pinv(K)
    inv_K = torch.from_numpy(inv_K)
    inv_K = inv_K.unsqueeze(0)

    with torch.no_grad():
        image = torch.autograd.Variable(image.cuda())
        inv_K = torch.autograd.Variable(inv_K.cuda())
        depth1_list, uncer1_list, depth2_list, uncer2_list, normals, _ = model(image, inv_K, epoch)
        if epoch < 5:
            pred_depth = 0.5 * (depth1_list + depth2_list)
        else:
            pred_depth = 0.5 * (depth1_list[-1] + depth2_list[-1])
        if post_process:
            image_flipped = flip_lr(image)
            depth1_list_flipped, uncer1_list_flipped, depth2_list_flipped, uncer2_list_flipped, normals_flipped, _ = model(image_flipped, inv_K, epoch)
            if epoch < 5:
                pred_depth_flipped = 0.5 * (depth1_list_flipped + depth2_list_flipped)
            else:
                pred_depth_flipped = 0.5 * (depth1_list_flipped[-1] + depth2_list_flipped[-1])
            pred_depth = post_process_depth(pred_depth, pred_depth_flipped)

        pred_depth = pred_depth.cpu().numpy().squeeze()

    pred_depth[pred_depth < args.min_depth_eval] = args.min_depth_eval
    pred_depth[pred_depth > args.max_depth_eval] = args.max_depth_eval
    pred_depth[np.isinf(pred_depth)] = args.max_depth_eval
    pred_depth[np.isnan(pred_depth)] = args.min_depth_eval
    
    
    pred_depth = pred_depth * 50
    cv2.imwrite("depth.png", pred_depth)
    
    normals = normals.cpu().numpy().squeeze()
    normals = normals.transpose(1, 2, 0)
    normals = np.array(normals) * 255
    cv2.imwrite("normals.png", normals)


def main_worker(args):

    # CRF model
    model = NewCRFDepth(version=args.encoder, inv_depth=False, max_depth=args.max_depth, pretrained=None)
    model.train()

    num_params = sum([np.prod(p.size()) for p in model.parameters()])
    print("== Total number of parameters: {}".format(num_params))

    num_params_update = sum([np.prod(p.shape) for p in model.parameters() if p.requires_grad])
    print("== Total number of learning parameters: {}".format(num_params_update))

    model = torch.nn.DataParallel(model)
    model.cuda()

    print("== Model Initialized")

    if args.checkpoint_path != '':
        if os.path.isfile(args.checkpoint_path):
            print("== Loading checkpoint '{}'".format(args.checkpoint_path))
            checkpoint = torch.load(args.checkpoint_path, map_location='cpu')
            model.load_state_dict(checkpoint['model'])
            print("== Loaded checkpoint '{}'".format(args.checkpoint_path))
            del checkpoint
        else:
            print("== No checkpoint found at '{}'".format(args.checkpoint_path))

    cudnn.benchmark = True

    # ===== Evaluation ======
    model.eval()
    with torch.no_grad():
        test(model, args.test_image_path, post_process=True)


def main():
    torch.cuda.empty_cache()
    args.distributed = False
    ngpus_per_node = torch.cuda.device_count()
    if ngpus_per_node > 1:
        print("This machine has more than 1 gpu. Please set \'CUDA_VISIBLE_DEVICES=0\'")
        return -1
    
    main_worker(args)


if __name__ == '__main__':
    main()

```

**Comment by ShuweiShao** [comment]
I think there may be the following problems: 
1. You may resize the image size to match the training resolution. 
2. The intrinsic matrix may be wrong. We convert the predicted normal and distance to depth in the 1/4 resolution. Besides, please also revise the corresponding intrinsic matrix when you resize the image size.
3.  You should convert the normal value to (0, 1) before saving it, for example, normal_est_norm = (normal_est_norm + 1) / 2.

**Comment by Minnchong** [comment]
This is a very inspiring issue @ShuweiShao @CanCanZeng 
There are some questions that I would like to consult with you.
1. When I tested the RGB image above using different models(kittieigen.pth and nyu.pth), the depth given was not the same
` pred_depth = pred_depth.cpu().numpy().squeeze()`
For the kittieigen.pth, the max_depth is 14.31; for the nyu.pth, the max_depth is 5.13.
2. Why is the factor here 50？
`pred_depth = pred_depth * 50`
3.“Besides, please also revise the corresponding intrinsic matrix when you resize the image size.”
II did not find this parameter (intrinsic matrix) in the project

**Comment by Minnchong** [comment]
This is a very inspiring issue @ShuweiShao @CanCanZeng 
There are some questions that I would like to consult with you.

1. When I tested the RGB image above using different models(kittieigen.pth and nyu.pth), the depth given was not the same
` pred_depth = pred_depth.cpu().numpy().squeeze()`
For the kittieigen.pth, the max_depth is 14.31; for the nyu.pth, the max_depth is 5.13.

2. Why is the factor here 50？
`pred_depth = pred_depth * 50`

3.“Besides, please also revise the corresponding intrinsic matrix when you resize the image size.”
II did not find this parameter (intrinsic matrix) in the project

**Comment by CanCanZeng** [comment]
@ShuweiShao Thank you for your help!
1. should I also crop the image? since the aspect ratio may be different
2. the intrinsic matrix is not very accurate, but already very close, since I transform the depth map to point cloud using the provided intrinsics, the point cloud is roughtly right.
3. OK, I converted the normal value to (0, 1), it looks to be right.

Have you tried omnidata? https://omnidata.vision/demo/ The output normal map of this algorithm seems to be pretty good even for very complicated scene. I guess this ascribes to their very rich dataset and a lot of work done to enhance robustness. And they do not use depth map captured by the camera directly, but do 3D reconstruction first, and then render the depth map. I don't know the reason for this, but is it possible to improve accuracy this way?

**Comment by CanCanZeng** [comment]
@Minnchong 
1. I do not care about the absolut value of mono depth, since the scale is not observable.
2. The 50 is meaningless, it's just for visualization.
3. You should revise the code to provide the intrinsics (`K`) of your image.

**Comment by ShuweiShao** [comment]
@CanCanZeng  I have not tried omnidata before.  Maybe you can have a try and share some results here.

**Comment by CanCanZeng** [comment]
@ShuweiShao The output of NDDepth and omnidata are listed bellow:
![normal_map](https://github.com/ShuweiShao/NDDepth/assets/26817559/387a5ee2-2e7a-4ec5-85ea-3ed7ae56274e)
![normal_map](https://github.com/ShuweiShao/NDDepth/assets/26817559/e614901c-bf29-4df2-a8cd-db2b907305d3)
you can see that the output normal map of NDDepth seems to be blurred and lose some details. I wonder the "blurred" effect is related to the quality of normal map of training dataset, since omnidata do not use the raw data from NYU normal dataset but the rendered normal map from reconstructed mesh.

**Comment by ShuweiShao** [comment]
Thanks for your sharing. Is this case from the NYU dataset? Which inference resolution has you setted?

**Comment by CanCanZeng** [comment]
No, the test image is not from opensource dataset, I took this photo in my room. I just noticed that most surface normal estimation algorithm NYU or Kitti dataset, but omnidata algorithm use much more training data https://github.com/EPFL-VILAB/omnidata/tree/main/omnidata_tools/dataset#readme
