### ISSUE TITLE
About generating normal map.

### ISSUE THREAD

**Issue by lliu00** [ShuweiShao/NDDepth#10]
Hi, thanks for your great work!
After reading the code, I find that there is no corresponding normal map. Could you please provide the download link for the normal map you generated? Thank you very much.

**Comment by ShuweiShao** [comment]
Hi, the generated normal maps can be downloaded from https://drive.google.com/file/d/1nITbaVeaEh8JikKV3LK_Vrc67XV9Jkeh/view?usp=drive_link (NYU)and https://drive.google.com/file/d/1__JhniUkOVaQHft2CXL5ZXqnmf-yUAOa/view?usp=drive_link (KITTI)
