### ISSUE TITLE
Error: Tensor Size Mismatch in compute_seg Function (utils.py)

### ISSUE THREAD

**Issue by QiuJunning** [ShuweiShao/NDDepth#11]
Hello! After running your program, I found that the lines `normD_down = D_down + norm_down` and `normD_right = D_right + norm_right` in the `utils.py` file, following the `compute_seg` function, are causing errors. The line `normD_down = D_down + norm_down` is giving a `RuntimeError: The size of tensor a (640) must match the size of tensor b (479) at non-singleton dimension 2`, where the shape of `D_down` is (1, 479, 640), and the shape of `norm_down` is (1, 3, 479). A similar issue is occurring with `normD_right`. I'm not sure how to resolve this. Looking forward to your response!

**Comment by ShuweiShao** [comment]
Hi, this may induced by the version of nn.PairwiseDistance(p=2). Please change 
 norm_down = pdist(aligned_norm[:, :, 1:], aligned_norm[:, :, :-1])
 norm_right = pdist(aligned_norm[:, :, :, 1:], aligned_norm[:, :, :, :-1])
to
 norm_down = pdist(aligned_norm[:, :, 1:].permute(0, 2, 3, 1), aligned_norm[:, :, :-1].permute(0, 2, 3, 1))
 norm_right = pdist(aligned_norm[:, :, :, 1:].permute(0, 2, 3, 1), aligned_norm[:, :, :, :-1].permute(0, 2, 3, 1))
and then have a try.

**Comment by QiuJunning** [comment]
Thank you, this works! Additionally, I've noticed that in train.py, it's necessary to add if args.multiprocessing_distributed: before group = dist.new_group([i for i in range(ngpus_per_node)]) to avoid encountering errors.

**Comment by ShuweiShao** [comment]
Received with thanks!
