### ISSUE TITLE
Uncertainty Modeling 

### ISSUE THREAD

**Issue by PetropoulakisPanagiotis** [ShuweiShao/NDDepth#14]
The implementation code for uncertainty is different than what is written in the paper. Could you please provide some insights for this choice?

**Comment by ShuweiShao** [comment]
Hi, both choices will be fine.  We normalize it here condisidering that  a unit depth difference, for example 1m, represents the different uncertainty between distant and nearby points in a scene, and it should be higher on the nearby points and less on the distant points.
