### ISSUE TITLE
Is there a DC version code?

### ISSUE THREAD

**Issue by YikangZhang1641** [ShuweiShao/NDDepth#15]
Thank you for sharing your excellent work.

NDDepth achieves good rankings on both KITTI Depth Completion and Prediction Benchmark, but only RGB images are loaded in NewCRFDepth(), so I wonder if there is a Depth Completion version which takes sparse depth map as optional input, or if you simply submitted the Prediction results and perfomed well.

**Comment by ShuweiShao** [comment]
Thanks for your attention. The DC version has not been released yet. We will release the whole code upon the acceptance.
