### ISSUE TITLE
About zero-shot testing on  SUN RGB-D

### ISSUE THREAD

**Issue by lliu00** [ShuweiShao/NDDepth#16]
Hi Shuwei, 
I noticed that NYU dataset uses the same camera intrinsics for depth calculation during testing, and the resolution remains consistent. However, in zero-shot, the camera intrinsics of the SUNRGBD dataset vary significantly across different scenes, and the resolutions are also different. Could you please tell me how to address this issue during testing? I appreciate your insights. Thank you!

**Comment by ShuweiShao** [comment]
Hi, we only resize the resolution of images from SUN RGB-D dataset to the training resolution for zero-shot setting.  But if you also modify the camera intrinsic, you may get better results.

**Comment by lliu00** [comment]
Thank you for your reply! I used NYU’s camera internal parameters to verify the performance in the paper.
I also tried using SUNRGBD's camera intrinsics and the performance dropped. This may be because the network learned the bias about the NYU camera intrinsics.
