### ISSUE TITLE
Pseudo-Lidar from Depth

### ISSUE THREAD

**Issue by ahtso** [ShuweiShao/NDDepth#17]
According previous issue,
you mentioned that the output depth maps were trained by supervised ground truth, so the depth is absolute distance, right?
But when I used inference_single_image.py to generate the predict depth map on kitti dataset, and turned the depth to 3D domain ( Pseudo-Lidar), and take the ground truth point cloud bin file from kitti dataset (velodyne),
put both Lidar(GT) an pseudo-lidar(pred) in same 3D domain.
My main question is that how to adjust the prediction depth to well map on GT lidar bin?
( It seems the depth scale is not ideal. )
Hope you could help me to figure out this, thanks.
( If Chinese is Ok, the next reply would type in Chinese, haha)

the output in Open3D tool looks like below:
![image](https://github.com/ShuweiShao/NDDepth/assets/30041220/9b7d23ea-d5ba-445d-8beb-70073fa3cbfe)

the so-called well mapping pseudo-lidar(from depth map) it might look like below (white part)
![image](https://github.com/ShuweiShao/NDDepth/assets/30041220/f509ecf1-c6d4-4748-991b-d4c7b45c09d6)

and the depth map output
![image](https://github.com/ShuweiShao/NDDepth/assets/30041220/e5f5e194-3723-4195-8e91-93ae4ba2689b)

**Comment by ShuweiShao** [comment]
Hi, Chinse is ok! Besides, which view of point cloud are you showing above?

**Comment by ahtso** [comment]
我利用open3D將點雲繪出，所以視角是可以調整的。
兩張點雲是相同的，上面那張是利用NDDepth 所產出的Pseudo-Lidar
但尺寸明顯跟原始Kitti的點雲不符(彩色光譜的點雲)
下面那張點雲是利用其他開源所產出的Pseudo-Lidar, 基本上透過外參就能與原始點雲匹配

主要是我透過 Model inference出來的結果，深度的數值似乎不是絕對距離？或者我該怎麼進行調整
(尤其影像正中間的遠方車輛)
我的深度圖是使用inference_single_image.py 所繪出

**Comment by ShuweiShao** [comment]
我也有点困惑，但模型应该输出的是绝对距离，因为采用的监督真值是具有绝对尺度的。

**Comment by ahtso** [comment]
照您說法，inference出來的深度圖，數值應該會落在0-80 ( KITTI資料集最遠達80m)
但我看了一下我的inference的深度圖，數值會落在0-255，這似乎不合理？
是否需要透過任何方式去放大縮小輸出的depth map?

**Comment by ShuweiShao** [comment]
不是的，0-255是因为将原始的深度图映射成了彩色图像方便可视化，你应该用网络预测的原始深度图。
