### ISSUE TITLE
about models

### ISSUE THREAD

**Issue by water221** [ShuweiShao/NDDepth#19]
Can you provide the model used by the project again? The link in the readme file has expired.

**Comment by water221** [comment]
Can you open source the model and dense_depth dataset? as shown
![image](https://github.com/ShuweiShao/NDDepth/assets/52553731/ca2611cb-e66d-44f0-8dee-61f163c87e38)

**Comment by ShuweiShao** [comment]
Please try it again. Just  ignore these images wth dense.
