### ISSUE TITLE
Need Permissions

### ISSUE THREAD

**Issue by shaopingLL** [ShuweiShao/NDDepth#22]
I want to test the scripts of train and inference, but I haven't the Permissions to download dataset of nyu normal and pertained model.

**Comment by ShuweiShao** [comment]
Please try it again.

**Comment by shaopingLL** [comment]
谢谢你的回复和分享，不胜感激




李少平
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShuweiShao/NDDepth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月13日(星期一) 晚上7:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ShuweiShao/NDDepth] Need Permissions (Issue #22)





 
Closed #22 as completed.
