### ISSUE TITLE
Need Permissions

### ISSUE THREAD

**Issue by anastasis199** [ShuweiShao/NDDepth#25]
Hello, I appreciate your excellent work! I'm looking to train using my own dataset by referring to the training code in this repository. I want to test the inference scripts, but I don't have permission for the pre-trained models (NYUv2 (Swin-L and KITTI_Eigen (Swin-L)). It needs an access code when choosing Google Drive.

**Comment by ShuweiShao** [comment]
Please try it again.

**Comment by anastasis199** [comment]
Thank you.
