### ISSUE TITLE
parameter settings

### ISSUE THREAD

**Issue by Minnchong** [ShuweiShao/NDDepth#3]
Thanks for your great work！ I have a small question for the parameter (inv_K). When I inference a wild picture, how should I set this parameter? Thank you in advance.

**Comment by ShuweiShao** [comment]
You could try the default intrinsic matrix.

**Comment by jay25208** [comment]
Is the model uses intrinsic matrix as input? Default intrinsic matrix for wild picture may cause scale ambiguity？
