### ISSUE TITLE
how to get normal map？

### ISSUE THREAD

**Issue by QiuJunning** [ShuweiShao/NDDepth#4]
I noticed that the dataset seemingly does not include normal maps. Could you please provide information on how this part is generated? Thank you!

**Comment by ShuweiShao** [comment]
Sorry for the late reply, I just found that the code to generate surface normal has been deleted in the original Github of DeepLiDAR. You may refer to https://github.com/wassryan/Deeplidar_v2 to acquire the code for urgent need.  I will continue to improve the NDDepth repository.
