### ISSUE TITLE
Cut_Flip doesn't take normal

### ISSUE THREAD

**Issue by jakubgregorek** [ShuweiShao/NDDepth#6]
The method Cut_Flip in DataLoadPreprocess is declared to take image and depth:

https://github.com/ShuweiShao/NDDepth/blob/84b6c6322efffc0e747d877b7dc4358570832d73/Estimation/nddepth/dataloaders/dataloader.py#L260

and it is called with image, depth and normal:

https://github.com/ShuweiShao/NDDepth/blob/84b6c6322efffc0e747d877b7dc4358570832d73/Estimation/nddepth/dataloaders/dataloader.py#L155

Is the implementation for normal missing or should this call be just removed?

**Comment by ShuweiShao** [comment]
Hi, I have fixed this error.
